name = "soul-safety"
compatibility_date = "2026-03-14"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "soul-safety"
database_id = "41999068-a0e3-4aeb-bca1-b8ca8d938258"
